### ISSUE TITLE
Issue deploying HA in Australia East

### ISSUE THREAD

**Issue by fakrul** [sophos-iaas/xg-azure-aa#3]
I am getting the following error while creatign the HA in Australia East:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidTemplateDeployment\",\r\n \"message\": \"The template deployment failed with error: 'The resource with id: '/subscriptions/757d80a3-44f4-4227-8105-2e744c3abcfe/resourceGroups/HIA-Azure-Sophos/providers/Microsoft.Compute/virtualMachines/sophosxg-ha-fw-0' failed validation with message: 'The requested size for resource '/subscriptions/757d80a3-44f4-4227-8105-2e744c3abcfe/resourceGroups/HIA-Azure-Sophos/providers/Microsoft.Compute/virtualMachines/sophosxg-ha-fw-0' is currently not available in location 'australiaeast' zones '' for subscription '757d80a3-44f4-4227-8105-2e744c3abcfe'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'.\"\r\n }\r\n}"}]}

Just wondering whether there is any restriction.

**Comment by jornlutters** [comment]
Hi Fakrul,

There are a few restrictions on this template:

1. You can't deploy on machines that do not meet minimum performance specs for XG Firewall, this means Standard_A0 and A1, Basic_A0 and A1, and Standard_B1s and Standard_B1ms are excluded.

2. Deploying into a region that does not support Azure Automation requires the use of an existing AA account in a different region.

3. You need to enable SSH access to the XG machines from anywhere (0.0.0.0/0) on first run to allow the automation script to work correctly

Beyond these restrictions we do not enforce anything ourselves; platform restrictions such as the number of fault domains in an AV set still apply obviously.

For more details on the XG AA deployment, check out our KB article here: https://community.sophos.com/kb/en-us/133755

**Comment by fakrul** [comment]
Hi, got the issue. It the VM Size I was choosing. Standard_D2_V2 is not available in Australia East.
